services:
  - type: web
    name: todo-flask-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    workingDir: backend
